# -*- coding: utf-8 -*-
"""EPS Goals Scored

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHpJbw-PczJy-xVcr9M4Fv0B6RtXQL8D
"""

!pip install squarify

import matplotlib
import matplotlib.pyplot as plt
import squarify
from bs4 import BeautifulSoup
import requests

BASE_URL = 'https://en.wikipedia.org/wiki/2021%E2%80%9322_Premier_League'
response = requests.get (BASE_URL)
soup = BeautifulSoup(response.content)

table = soup.select_one('#League_table') .parent.find_next_sibling('table')

rows = table.find_all('tr') [1:]

team_data = []

for row in rows:
  team_name = row.find('th').text.strip()

  gf = row.find_all('td')[5].text.strip()
  team_data.append({
      'name': team_name,
      'scored': int(gf)
  })

team_data

team_data.sort(key=lambda x: x['scored'], reverse=True)
scored = [team['scored'] for team in team_data]
names = [f"{team['name']}\n{team['scored']}" for team in team_data]

norm = matplotlib.colors.Normalize(vmin=min(scored), vmax=max(scored))
colors = [matplotlib.cm.Reds(norm(value)) for value in scored]

fig, ax = plt.subplots(figsize=(10,10))
squarify.plot(sizes=scored, label = names[:20], color=colors)

names = [team['name'] for team in team_data]
fig, ax = plt.subplots(figsize=(10, 7))

plt.barh(y=names, width=scored)
plt.title("Goals Scored in EPL 2021-2022", fontsize =18)
plt.xlabel('Goals Scored')
plt.ylabel('Team Name')
plt.show()